services:
  # Define service for ROS workspace
  gen3_tutorial:
    # Build Docker image using Dockerfile in docker directory
    build: docker
    # Set container name for easy reference
    container_name: gen3_tutorial_container
    # Use NVIDIA runtime for GPU support
    runtime: nvidia 
    environment:
    # Enable access to all NVIDIA GPUs inside container
    - NVIDIA_VISIBLE_DEVICES=all
    # Enable all NVIDIA driver capabilities (compute, utility, graphics etc.)
    - NVIDIA_DRIVER_CAPABILITIES=all 
    # Forward X11 display from host to enable GUI applications
    - DISPLAY=$DISPLAY
    # Fix for Qt applications rendering issues in containerized X11
    - QT_X11_NO_MITSHM=1
    # Set ROS node hostname for local networking
    - ROS_HOSTNAME=localhost

    volumes:
      # Mount host /dev directory for USB device access
      - /dev:/dev
      # Mount X11 socket for GUI applications
      #- /tmp/.X11-unix:/tmp/.X11-unix:rw

    # Grant extended privileges to container
    privileged: true
    # Enable interactive terminal
    tty: true
    # Use host network stack
    network_mode: host

    # Source the ROS 2 Humble setup script
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && /bin/bash"